### DISCUSSION TITLE
Correct way to expose custom statsd port?

### DISCUSSION THREAD

**Discussion by paymog** [vectordotdev/helm-charts#317] [Q&A] [answered]
I want to a statsd source to my `customConfig` like so:

```
role: Agent
customConfig:
  data_dir: /vector-data-dir
  api:
    enabled: false
  sources:
    ...other sources
    statsd-metrics:
      type: statsd
      address: 0.0.0.0:9831
      mode: udp
  sinks:
    ...
```

What's the canonical way to then expose port `9831` so that other pods in the cluster can submit statsd metrics to vector? 

Additionally, what's the right way to configure pods to submit statsd metrics to vector? The docs for the datadog agent suggest using an env var like so:

```
    - name: DD_AGENT_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
```

When using statsd with vector, should similar config be used on pods which want to send statsd metrics to the vector pods?

**Comment by paymog** [comment, marked as answer]
Figured it out! I added the following to my helm values file

```
containerPorts:
  - name: statsd
    containerPort: 9831
    protocol: UDP
    hostPort: 9831
```

And did use the following config for getting my pods to communicate with vector

```
    - name: STATSD_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: STATSD_PORT
       value: 9831
```
