### DISCUSSION TITLE
Vector events in disk buffer not preserved after pod restart

### DISCUSSION THREAD

**Discussion by viktordebulat** [vectordotdev/helm-charts#375] [Q&A] [answered]
When restarting pod with disk buffer persistence enabled vector buffer doesn't try to send already got events from kafka but starts from 0 with current consumer, so events are lost. How this issue could be resolved or I missed something?

Use 0.31.0 chart version (the same issue was on 0.26.0 version too, so bump didn't help)

Persistence is enabled:
```
          persistence:
            enabled: true
            storageClassName: premium-rwo
            size: 10Gi
```

Typical sink config.

```
            sinks:  
              clickhouse:
                type: clickhouse
                healthcheck: true
                acknowledgements:
                  enabled: true
                inputs: ["kafka"]
                endpoint: _lorem-ipsum_
                database: _lorem-ipsum_
                table: _lorem-ipsum_
                skip_unknown_fields: true
                auth:
                  strategy: basic
                  user: vector
                  password: _lorem-ipsum_
                buffer:
                  type: disk
                  max_size: 5368709120
                  when_full: block
                batch:
                  max_bytes: 536870912
                  timeout_secs: 5
                request:
                  timeout_secs: 120
```

P.S. Using Aggregator role with 1 replica

**Comment by jszwedko** [comment]
Nothing immediately jumps out. Have you verified that when the pod is restarted, the volume is reattached with all of the disk buffer files contained? These would be in `/var/lib/vector` in the container.

**Reply by viktordebulat** [reply]
The same volume, re-attached after restart (have SuccessfulAttachVolume event, same volume). Volume mount as usual, not changed

```
    volumeMounts:
    - mountPath: /vector-data-dir
      name: data
```

```
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data-clickhouse-test-vector-0
```

Attached vector top before restart
<img width="1602" alt="Screenshot 2024-02-21 at 21 43 26" src="https://github.com/vectordotdev/helm-charts/assets/43744974/3cb3f38e-36b1-4e21-8664-911deed53f7a">

And after restart:
<img width="1602" alt="Screenshot 2024-02-21 at 21 45 18" src="https://github.com/vectordotdev/helm-charts/assets/43744974/2f5d7d4a-dd40-4bea-b7bc-0f4e58ca115b">
