### ISSUE TITLE
Templating error with loki labels

### ISSUE THREAD

**Issue by rlex** [vectordotdev/helm-charts#106]
Hello, tried to deploy vector with helm using recommended values for label, still fails with "failed to find function file". Sample values:

```yaml
role: Agent
customConfig:
  data_dir: "/vector-data-dir"
  sinks:
    prometheus:
      address: "0.0.0.0:9090"
      inputs: ["internal_metrics", "host_metrics"]
      type: "prometheus"
    loki:
      inputs: ["kubernetes_logs"]
      type: "loki"
      endpoint: "https://loki-ingress"
      auth:
        strategy: basic
        user: loki
        password: loki
      remove_timestamp: true
      tenant_id: kube
      encoding: json
      labels:
        forwarder: "vector"
        file: |
          {{ file }}
        stream: |
          {{ stream }}
        source_type: |
          {{ source_type }}
        k8s_pod_namespace: |
          {{ kubernetes.pod_namespace }}
        k8s_pod_name: |
          {{ kubernetes.pod_name }}
        k8s_pod_uid: |
          {{ kubernetes.pod_uid }}
        k8s_pod_ip: |
          {{ kubernetes.pod_ip }}
        k8s_pod_ips: |
          {{ kubernetes.pod_ips }}
        k8s_pod_node_name: |
          {{ kubernetes.pod_node_name }}
        k8s_app: |
          {{ kubernetes.pod_labels.app }}
        k8s_kubernetes_io_instance: |
          {{ kubernetes.pod_labels.app\.kubernetes\.io/instance}}
        k8s_kubernetes_io_component: |
          {{ kubernetes.pod_labels.app\.kubernetes\.io/component }}
        k8s_kubernetes_io_name: |
          {{ kubernetes.pod_labels.app\.kubernetes\.io/name }}
        k8s_container_name: |
          {{ kubernetes.container_name }}
        k8s_container_image: |
          {{ kubernetes.container_image }}
  sources:
    kubernetes_logs:
      type: "kubernetes_logs"
    host_metrics:
      type: "host_metrics"
    internal_metrics:
      type: "internal_metrics"
```
