### ISSUE TITLE
ArgoCD always thinks the Vector HPA is out of sync.

### ISSUE THREAD

**Issue by sam-mcbr** [vectordotdev/helm-charts#118]
Due to the order of the spec.metrics list for the HPA, Argo will consider the HPA permanently out of sync:

<img width="961" alt="Screen Shot 2021-11-23 at 1 13 42 PM" src="https://user-images.githubusercontent.com/86423878/143082498-3816216a-7727-4414-ace9-abfbb1aa7beb.png">

**Comment by spencergilbert** [comment]
Ah, the pain of GitOps 😵‍💫

**Comment by CmdrSharp** [comment]
Just as a fun aside (since I found this) - for me, the HPA Controller thinks the _opposite_ order is correct. I told Argo to ignore differences on that resource.

```yaml
      ignoreDifferences:
      - group: autoscaling
        kind: HorizontalPodAutoscaler
        jsonPointers:
        - /spec/metrics
```

This is tracked as a Kubernetes bug, by the by.
https://github.com/kubernetes/kubernetes/issues/74099
