### ISSUE TITLE
Custom config : how pass credentials

### ISSUE THREAD

**Issue by nlamirault** [vectordotdev/helm-charts#130]
Hi,
In the custom config field, i would like to pass credentials like : 

```yaml
customConfig:
  honeycomb:
    type: honeycomb
    inputs:
    - kubernetes_logs
    rawConfig: |
      api_key = "xxxxxx"
      dataset = "xxxxxx"
      healthcheck.enabled = true
```

how can i do that using the chart ? it is possible to use a secret which contains all the configuration ?
Thanks.
