### ISSUE TITLE
vector: ClusterRole missing common labels

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/helm-charts#141]
https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/templates/rbac.yaml
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vector.fullname" . }}
rules:
...
```
