### ISSUE TITLE
Vector can't connect to Splunk sink on Kubernetes cluster node

### ISSUE THREAD

**Issue by erdogancel** [vectordotdev/helm-charts#151]
Hi all!

We are using the official Helm chart version 0.3.0 with the below config bypassing to `customConfig`

role: Agent
    containerPorts:
      - containerPort: 19000
        hostPort: 19000
        name: tcp
    customConfig:
      data_dir: /var/lib/vector
      api:
        enabled: true
        address: 127.0.0.1:8686
        playground: false
      ...

Vector having a problem connecting `splunk_uf_tcp` below. Can someone help me with this issue?

The sink is
 splunk_uf_tcp:
    type: socket
    inputs:
      - key_value_extractor
    address: 0.0.0.0:19001
    mode: "tcp"
    encoding: "text"

2022-01-14T15:32:05.307438Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info"
2022-01-14T15:32:05.307514Z  INFO vector::app: Loading configs. paths=["/etc/vector"]
2022-01-14T15:32:05.315591Z  WARN vector::tls::settings: The `verify_hostname` option is DISABLED, this may lead to security vulnerabilities.
2022-01-14T15:32:05.328073Z  WARN vector::tls::settings: The `verify_hostname` option is DISABLED, this may lead to security vulnerabilities.
2022-01-14T15:32:05.339441Z  INFO vector::topology::running: Running healthchecks.
2022-01-14T15:32:05.339484Z  INFO vector::topology::running: Starting source. key=app_source_tcp1
2022-01-14T15:32:05.339515Z  INFO vector::topology::running: Starting transform. key=key_value_extractor
2022-01-14T15:32:05.339527Z  INFO vector::topology::running: Starting sink. key=daas
2022-01-14T15:32:05.339535Z  INFO vector::topology::running: Starting sink. key=splunk_uf_tcp
2022-01-14T15:32:05.339576Z  INFO vector: Vector has started. debug="false" version="0.19.0" arch="x86_64" build_id="da60b55 2021-12-28"
2022-01-14T15:32:05.339590Z  INFO vector::internal_events::api: API server running. address=127.0.0.1:8686 playground=off
2022-01-14T15:32:05.339742Z  INFO source{component_kind="source" component_id=app_source_tcp1 component_type=socket component_name=app_source_tcp1}: vector::sources::util::tcp: Listening. addr=0.0.0.0:19000
2022-01-14T15:32:05.340324Z ERROR vector::topology::builder: msg="Healthcheck: Failed Reason." error=Connect error: Connection refused (os error 111) component_kind="sink" component_type="socket" component_id=splunk_uf_tcp component_name=splunk_uf_tcp

**Comment by jszwedko** [comment]
Hi @erdogancel !

The address you are using for Splunk, `0.0.0.0:19001`, will only work if Splunk is running and bound to localhost (which would mean in the same container as Vector). Given you are running in k8s I'm guessing this is unlikely to be the case. I think you need to figure out what the correct address is to use for the remote Splunk instance.

**Comment by erdogancel** [comment]
Hi @jszwedko ! Thank you for the prompt response.

Splunk and  Vector both running as DaemonSet so they create a pod on the each k8 node. 

I commented out the Splunk but and realized apps can't even send logs to Vector to insert them in our ELK cluster. 

Our apps are set up to send the logs to port 19000 in the k8 cluster. 

I still think the issue with ports are not available for app pods to send logs to Vector.

Any thoughts? 

Thank you!

```
values:
  role: Agent
  containerPorts:
    - containerPort: 19000
      hostPort: 19000
      name: tcp
  service:
    ports:
      - name: tcp-logging
        port: 19000
        protocol: TCP
        targetPort: 19000
  customConfig:
    api:
      enabled: true
      address: 0.0.0.0:8686
      playground: false
    sources:
      app_source_tcp1:
        type: "socket"
        address: "0.0.0.0:19000"
        mode: "tcp"
        host_key: "host.hostname"
    transforms:
      key_value_extractor:
        type: remap
        inputs:
          - "app_source_tcp1"
        source: . = parse_key_value!(.message)
    sinks:
      saads:
        type: elasticsearch
        inputs:
          - "key_value_extractor"
        endpoint: <Internal ELK URL>
        bulk:
          action: "create"
          index: <An Index>
        auth:
          strategy: "basic"
        batch:
          max_bytes: 10490000
          timeout_secs: 8
        buffer:
          type: "disk"
          max_size: 1049000000
          when_full: "drop_newest"
        tls:
          verify_hostname: false
```
