### ISSUE TITLE
Consider automagic generation of HAProxy configuration

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/helm-charts#155]
We ran across a user today that was attempting to provide a `customConfig` for Vector and enable HAProxy (`haproxy.enabled: true`) but was not aware that they'd then need to provide an additional `haproxy.customConfig` describing the HAProxy configuration.

We currently do some automagic exposing of ports based on Vector configs when `customConfig` is provided. It seems like we could potentially do something similar here to generate the HAProxy config based on the Vector configuration.

Example `values.yaml` that fails to deploy:

```
haproxy:
  enabled: true
customConfig:
  data_dir: /var/lib/vector
  api:
    enabled: false
  sources:
    auth0:
      type: http
      address: 0.0.0.0:80
      encoding: ndjson
  sinks:
    console:
      type: console
      inputs:
        - auth0
      encoding:
        codec: json
```
