### ISSUE TITLE
Consider support of transforms in separate files (tests context)

### ISSUE THREAD

**Issue by zhenik** [vectordotdev/helm-charts#171]
Are there any support of tests available? 

Like with opportunity to run test (as part of CD/CI)
```shell
vector test -C transforms/
```

I maintly though about tests of transforms from customConfig in separate files. Something like that

**Structure**
```
.
├── transforms
│   ├── transform_0.yaml
│   └── transform_1.yaml
└── values.yaml
```

**Files**  
values.yaml
```
...
customConfig:
  sources:
    kubernetes_logs:
      type: kubernetes_logs
  transforms: |-
    {{- include "transforms/transform_0.yaml" . | indent 4 }}
    {{- include "transforms/transform_1.yaml" . | indent 4 }}
  sinks:
    stdout:
      type: console
      inputs: [ transform_1, transform_0, ... ]
      encoding:
        codec: json
```

transform_1.yaml
```
transform_1:
  type: filter
  inputs:
    - kubernetes_logs
  condition: '.source == "local"'

tests:
  - name: Filter with positive
    inputs:
      - type: log
        insert_at: transform_1
        log_fields:
          source: "local"
          field_1: 14
    outputs:
      - extract_from: transform_1
        conditions:
          - exists(.field_1)
          - .field_1 == 14
```
