### ISSUE TITLE
Output Datadog Helm Chart values on install

### ISSUE THREAD

**Issue by silversupreme** [vectordotdev/helm-charts#177]
When we setup a customer using the `datadog_agent` source, it would be extremely helpful to have the chart emit the necessary configuration to properly wire the agent up to the new Aggregator.

This would need to be updated once the `vector` config options land in the Agent, but should suffice for now:

```yaml
datadog:
  # These need to be enabled for the Agent to even collect logs at all.
  logs:
    enabled: true
    containerCollectAll: true

  # Don't collect Vector logs so we can avoid a logging loop.
  containerExclude: "image:vector"

  # Override the Logs Agent to point to Vector instead.
  env:
    - name: DD_LOGS_CONFIG_DD_URL
      value: "${URL}"
    - name: DD_LOGS_CONFIG_USE_HTTP
      value: "true"
```

**Comment by spencergilbert** [comment]
Think the `env` based settings are better/easier than the [`YAML`](https://github.com/vectordotdev/vector-demos/blob/main/eks-aggregator/helm/datadog.yaml#L13-L20)?

**Comment by silversupreme** [comment]
I think that's entirely fair. I'll amend the description accordingly.

**Comment by spencergilbert** [comment]
Going through the quickstart work https://github.com/vectordotdev/helm-charts/pull/176, I think we'll need to provide it more like:
```yaml
datadog:
  containerExclude: "name:vector"
  logs:
    enabled: true
    containerCollectAll: true
agents:
  useConfigMap: true
  customAgentConfig:
    kubelet_tls_verify: false
    logs_config:
      logs_dd_url: {URL}
      logs_no_ssl: true
      use_http: true
```
