### ISSUE TITLE
Reintroduce `base` for image config

### ISSUE THREAD

**Issue by onedr0p** [vectordotdev/helm-charts#237]
Hi 👋🏼 

I saw this was removed with the switch to the new vector chart. I am running vector agent with the debian flavor of the image because it includes `journalctl`

```yaml
image:
  repository: timberio/vector
  tag: 0.23.3-debian
```

It would be nice if we could set a `flavor` or `base` config defining the image type we want to use:

```yaml
image:
  repository: timberio/vector
  base: debian # or flavor: debian
```

The reason I see this being helpful is that as a consumer of the chart when I go to update the chart version, I also need to update the `values.yaml` file with the new vector image. It would be nice to only care about the chart version instead of the chart version and image tag.

Thanks!
