### ISSUE TITLE
selectorLabels is same for different releases

### ISSUE THREAD

**Issue by nthienan** [vectordotdev/helm-charts#282]
I install two different releases using the same helm chart version. Here are results:

Deployment 1:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-1
  labels:
    app.kubernetes.io/component: Stateless-Aggregator
    app.kubernetes.io/instance: vector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vector
    app.kubernetes.io/version: 0.27.0-distroless-libc
    helm.sh/chart: vector-0.19.0
  namespace: vector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: Stateless-Aggregator
      app.kubernetes.io/instance: vector
      app.kubernetes.io/name: vector
  template:
    metadata:
      labels:
        app.kubernetes.io/component: Stateless-Aggregator
        app.kubernetes.io/instance: vector
        app.kubernetes.io/name: vector
...
```

Service 1:
```
apiVersion: v1
kind: Service
metadata:
  name: release-1
  labels:
    app.kubernetes.io/component: Stateless-Aggregator
    app.kubernetes.io/instance: vector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vector
    app.kubernetes.io/version: 0.27.0-distroless-libc
    helm.sh/chart: vector-0.19.0
  namespace: vector
spec:
  selector:
    app.kubernetes.io/component: Stateless-Aggregator
    app.kubernetes.io/instance: vector
    app.kubernetes.io/name: vector
...
```

Deployment 2:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-2
  labels:
    app.kubernetes.io/component: Stateless-Aggregator
    app.kubernetes.io/instance: vector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vector
    app.kubernetes.io/version: 0.27.0-distroless-libc
    helm.sh/chart: vector-0.19.0
  namespace: vector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: Stateless-Aggregator
      app.kubernetes.io/instance: vector
      app.kubernetes.io/name: vector
  template:
    metadata:
      annotations:
        checksum/config: ed025195ece807be01d17aca69cacefc2e4aa428ca7abfab79fff0619074620d
      labels:
        app.kubernetes.io/component: Stateless-Aggregator
        app.kubernetes.io/instance: vector
        app.kubernetes.io/name: vector
...
```

Service 2:
```
apiVersion: v1
kind: Service
metadata:
  name: release-2
  labels:
    app.kubernetes.io/component: Stateless-Aggregator
    app.kubernetes.io/instance: vector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vector
    app.kubernetes.io/version: 0.27.0-distroless-libc
    helm.sh/chart: vector-0.19.0
  namespace: vector
spec:
  selector:
    app.kubernetes.io/component: Stateless-Aggregator
    app.kubernetes.io/instance: vector
    app.kubernetes.io/name: vector
...
```

selector is same for both releases. This causes many problems
