### ISSUE TITLE
CustomConfig: Sink should not expose port

### ISSUE THREAD

**Issue by jkapusi** [vectordotdev/helm-charts#292]
I have a deployment that collects logs from another vector instance, does some transformation using remap, then sends them to another vector instance.

My values look like this:
```
customConfig:
  sources:
    vector:
      type: vector
      address: 0.0.0.0:9000
      version: 2
  transforms:
    parser:
      ...
  sinks:
    storage:
      type: vector
      inputs: ["parser"]
      address: storagehost:9000
```

When I try to apply it, I got a Duplicate value: core.ServicePort{} error, in the generated service definition there are two ports defined.
"vector" with port 9000, and "storage" with the same port 9000.

The helper function generates it here:
https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/templates/_helpers.tpl#L145-L150

Is there any use case where sink should expose a port?
