### ISSUE TITLE
Chart is running a single pod for role Agent

### ISSUE THREAD

**Issue by sondrelg** [vectordotdev/helm-charts#296]
Hi!

I'm running the `vector` helm chart v0.21 (latest) using `role: "Agent"`. The helm chart successfully deploys a `DaemonSet`, and each of the `DaemonSet` pods run successfully.

What confuses me slightly, and what I think seems like a bug, is that the helm chart also deploys a `StatefulSet` and a single pod.

![image](https://user-images.githubusercontent.com/25310870/232715144-f0fcdfc2-c574-4013-bdc3-de6760b120e3.png)

I tried setting `replicas: 0`, but that did not help. I have no other relevant chart configuration deviating from the defaults.

**Comment by sondrelg** [comment]
Looks like it's related to the headless service which I can't get rid of despite adding:

```
serviceHeadless:
  enabled: false
```

**Comment by sondrelg** [comment]
This is my full values.yaml-file, from which at least the service-account option, role option, and `customConfig` is loaded correctly:

```yaml
role: "Agent"

service:
  enabled: false

serviceHeadless:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 6000m
    memory: 1024Mi

envFrom:
  - secretRef:
      name: logtail-token-secret

customConfig:
  data_dir: /vector-data-dir
  api:
    enabled: false
    address: 127.0.0.1:8686
    playground: false
  sources:
    logtail_kubernetes_logs:
      type: kubernetes_logs
      self_node_name: "'$${VECTOR_SELF_NODE_NAME}'"
    host_metrics:
      type: host_metrics
  transforms:
    logtail_kubernetes_parser:
      type: remap
      inputs: [logtail_kubernetes_logs]
      source: >
        # this section is 200 loc, so I've cut it
  sinks:
    logtail_http_sink:
      type: http
      method: post
      uri: https://in.logtail.com/
      inputs: [logtail_kubernetes_parser]
      encoding:
        codec: json
      auth:
        strategy: "bearer"
        token: "'$${LOGTAIL_TOKEN}'"
```
