### ISSUE TITLE
Issue with customConfig Vector Templating

### ISSUE THREAD

**Issue by csongpaxos** [vectordotdev/helm-charts#314]
I see the below customConfig example in the README. However, for some reason when I try to use that same syntax, I am getting the issue that the s3 tag is malformed, because it thinks the tag itself is  `{{ container_name }}`, not the actual value of the container_name (which is a field in the log). I've tried ` {{ .container_name }}` and some others but to no avail. Not sure if I am missing something here.

README example:
```
customConfig:
  #...
  sinks:
    loki:
      #...
      labels:
        foo: bar
        host: |-
          {{ print "{{ host }}" }}
        source: |-
          {{ print "{{ source_type }}" }}
```

My values file contains:
```
  customConfig:
    data_dir: /var/lib/vector
    sources:
      kubernetes_logs:
        type: kubernetes_logs
    sinks:
      s3:
        type: aws_s3
       ...
       ...
        tags:
          splunk_index: test
          splunk_sourcetype: |-
            {{ print "{{ container_name }}" }}
```
