### ISSUE TITLE
mountpoints instead of mountPoints

### ISSUE THREAD

**Issue by jonathanlking** [vectordotdev/helm-charts#376]
I believe these should both be `mountpoints` instead of `mountPoints`:

https://github.com/vectordotdev/helm-charts/blob/afdcb836f2004eed7197b105d777c9fd3698c28f/charts/vector/templates/configmap.yaml#L72
https://github.com/vectordotdev/helm-charts/blob/afdcb836f2004eed7197b105d777c9fd3698c28f/charts/vector/docs/Migrate_from_vector-agent.md?plain=1#L35

With the following config:

```yaml
sources:
  host_metrics:
    filesystem:
      mountPoints:
        excludes:
        - '*/proc/sys/fs/binfmt_misc'
    type: host_metrics
sinks:
  blackhole:
```

Switching to `mountpoints` I get the diff (when passing through `vector convert-config --output-format json`):

```diff
63,66c63,66
<           "includes": [
<             "*"
<           ],
<           "excludes": null
---
>           "includes": null,
>           "excludes": [
>             "*/proc/sys/fs/binfmt_misc"
>           ]
```

This indicates `mountPoints` isn't being read from.

The documentation at https://vector.dev/docs/reference/configuration/sources/host_metrics/#warnings also refers to `mountpoints` and it would explain why I've still been getting the k8s "Too many levels of symbolic links" errors 😅
