### ISSUE TITLE
Vector fails to start with a Loki sink and k8 source, error function "kubernetes" not defined

### ISSUE THREAD

**Issue by ygenie418** [vectordotdev/helm-charts#440]
Vector fails to start with a Loki sink and k8 source

The error:
```
Error: UPGRADE FAILED: template: vector/templates/daemonset.yaml:32:28: executing "vector/templates/daemonset.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: e
rror calling include: template: vector/templates/configmap.yaml:11:3: executing "vector/templates/configmap.yaml" at <tpl (toYaml .Values.customConfig) .>: error calling tpl: erro
r during tpl function execution for "api:\n  address: 127.0.0.1:8686\n  enabled: true\n  playground: false\ndata_dir: /vector-data-dir\nsinks:\n  loki:\n    encoding:\n      codec
: json\n    endpoint: http://vector-loki-gateway.logging-tests.svc.cluster.local/\n    inputs:\n    - k8\n    labels:\n      '\"pod_labels_*\"': '{{ kubernetes.pod_labels }}'\n
   source: vector\n    out_of_order_action: accept\n    path: /loki/api/v1/push\n    type: loki\nsources:\n  k8:\n    auto_partial_merge: true\n    delay_deletion_ms: 60000\n    g
lob_minimum_cooldown_ms: 60000\n    type: kubernetes_logs": parse error at (vector/templates/daemonset.yaml:14): function "kubernetes" not defined
```

Using the following vector config:
```yaml
customConfig:
  data_dir: /vector-data-dir
  api:
    enabled: true
    address: 127.0.0.1:8686
    playground: false

  sources:
    k8:
      type: kubernetes_logs
      auto_partial_merge: true
      delay_deletion_ms: 60000
      glob_minimum_cooldown_ms: 60000

  sinks:
    stdout:
      type: console
      inputs:
        - k8
      encoding:
        codec: json

    loki:
      type: loki
      inputs:
        - k8
      endpoint: http://vector-loki-gateway.logging-tests.svc.cluster.local/
      encoding:
        codec: json
      out_of_order_action: accept
      path: /loki/api/v1/push
      labels:
        '"pod_labels_*"': "{{ kubernetes.pod_labels }}" # <------ Works fine without this
        source: vector
```

Both the source and sink examples were pulled from the docs. It seems I'm missing something with the templating?

I can confirm the event object does have those fields. Sample event:
```json
{
   "file":"...",
   "kubernetes":{
      ...
   },
   "message":"...",
   "source_type":"kubernetes_logs",
   "stream":"stdout",
   "timestamp":"2025-01-08T18:52:28.846545421Z"
}
```

vector version: 0.43.1
helm chart version: 0.38.1

Edit: typos
