### ISSUE TITLE
"failed to provide credentials provider=EcsContainer" when using AWS EKS Pod Identity

### ISSUE THREAD

**Issue by arseny-zinchenko** [vectordotdev/helm-charts#452]
I'm trying to run Vector from the Helm chart, and use the [AWS EKS Pod Identity](https://docs.aws.amazon.com/eks/latest/userguide/pod-id-how-it-works.html) for Vector to access AWS S3 and SQS.
Bt after creating all necessary resources (EKS Pod Identity associations to the Vector's ServiceAccount), Vector looks like wan't use it:

> atlas-victoriametrics-vector-0:vector 2025-02-14T12:01:55.145163Z  WARN source{component_kind="source" component_id=s3-vector-vmlogs-flow-logs-bucket component_type=aws_s3}:lazy_load_identity: aws_config::meta::credentials::chain: provider failed to provide credentials provider=EcsContainer error=the credentials provider was not properly configured: invalid full URI for ECS provider (URI did not refer to the loopback interface): http://169.254.170.23/v1/credentials (InvalidConfiguration(InvalidConfiguration { source: "invalid full URI for ECS provider (URI did not refer to the loopback interface): http://169.254.170.23/v1/credentials" }))

All necessary env variables for the Pod are set:
```
    Environment:
      VECTOR_LOG:                              info
      AWS_STS_REGIONAL_ENDPOINTS:              regional
      AWS_DEFAULT_REGION:                      us-east-1
      AWS_REGION:                              us-east-1
      AWS_CONTAINER_CREDENTIALS_FULL_URI:      http://169.254.170.23/v1/credentials
      AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE:  /var/run/secrets/pods.eks.amazonaws.com/serviceaccount/eks-pod-identity-token
```
S3 Source config:
```
    sources:
      s3-vector-vmlogs-flow-logs-bucket:
        type: aws_s3
        region: us-east-1
        compression: gzip
        auth:
          region: us-east-1
        sqs:
          queue_url: https://sqs.us-east-1.amazonaws.com/<ACCOUNT_ID>/s3-vector-vmlogs-queue
```
