### ISSUE TITLE
Add ingress to vector chart

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/helm-charts#52]
Needed to create an AWS ALB

ex:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vector
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/healthcheck-port: '8686'
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 8080}]'
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - host: vector.demo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vector
                port:
                  name: datadog-agents
```
