### ISSUE TITLE
Only expose a service port once

### ISSUE THREAD

**Issue by Yasumoto** [vectordotdev/helm-charts#77]
We should only expose one service port for listening in different modes.

For example, if we have a `customConfig` listening on a port for both `tcp` and `udp`:

```yaml
sources:                                                                                                                                                                                                                              
  syslog-tcp:                                                                                                                                                                                                                         
    type: syslog                                                                                                                                                                                                                      
    address: 0.0.0.0:514                                                                                                                                                                                                              
    max_length: 102400                                                                                                                                                                                                                
    mode: tcp                                                                                                                                                                                                                         
    shutdown_timeout_secs: 30                                                                                                                                                                                                         
  syslog-udp:                                                                                                                                                                                                                         
    type: syslog                                                                                                                                                                                                                      
    address: 0.0.0.0:514                                                                                                                                                                                                              
    max_length: 102400                                                                                                                                                                                                                
    mode: udp                                                                                                                                                                                                                         
    shutdown_timeout_secs: 30
```

We receive an error

```
Error: Service "vector01" is invalid: spec.ports[1]: Duplicate value: core.ServicePort{Name:"", Protocol:"TCP", AppProtocol:(*string)(nil), Port:514, TargetPort:intstr.IntOrString{Type:0, IntVal:0, StrVal:""}, NodePort:0}
```
