### ISSUE TITLE
Problem HaProxy and aggregator

### ISSUE THREAD

**Issue by rstreics** [vectordotdev/helm-charts#88]
When vector agent tries to send log via HaProxy to aggregator I getting problem.  
```
 WARN sink{component_kind="sink" component_id=aggregator_sink component_type=vector 
component_name=aggregator_sink}:request{request_id=304}: vector::sinks::util::retries: Retrying after error. error=Request failed: status: Internal, message: "protocol error: received message with invalid compression flag: 60 (valid flags are 0 and 1) while receiving response with status: 502 Bad Gateway", details: [], metadata: MetadataMap { headers: {"content-length": "107", "cache-control": "no-cache", "content-type": "text/html"} }
```
Haproxy config: https://pastebin.com/uR4ZCXDC
agent config
```
 sinks:
    aggregator_sink:
      type: vector
      inputs: ["kubernetes_logs"]
      address: vector-haproxy:6000
      version: "2"
```

aggregator config
```
 sources:
      vector:
        address: 0.0.0.0:6000
        type: vector
        version: "2"
```

logs haproxy
```
::ffff:10.0.1.139:39978 [18/Oct/2021:15:58:22.990] vector vector/srv1 1001/0/0/-1/1001 502 209 - - PH-- 3/3/0/0/0 0/0 "POST http://vector-haproxy:6000/vector.Vector/PushEvents HTTP/2.0"
::ffff:10.0.3.92:50390 [18/Oct/2021:15:58:23.634] vector vector/srv1 400/0/1/-1/400 502 209 - - PH-- 3/3/0/0/0 0/0 "POST http://vector-haproxy:6000/vector.Vector/PushEvents HTTP/2.0"
::ffff:10.0.3.92:50390 [18/Oct/2021:15:58:24.034] vector vector/srv1 124/0/0/-1/124 502 209 - - PH-- 3/3/0/0/0 0/0 "POST http://vector-haproxy:6000/vector.Vector/PushEvents HTTP/2.0"
```
